### ISSUE TITLE
Main image should take exactly full height of screen

### ISSUE THREAD

**Issue by rudnitskih** [Stan0men/Stan0men.github.io#25]
![image](https://user-images.githubusercontent.com/8848858/47778594-e0239680-dcff-11e8-946b-811c1ead64c4.png)

**Comment by Stan0men** [comment]
![02-11-2018 180717](https://user-images.githubusercontent.com/23480671/47926802-2b89a080-deca-11e8-8016-66bd3f5defa0.png)

**Comment by rudnitskih** [comment]
чет не взлетело:) Пробуй еще
![image](https://user-images.githubusercontent.com/8848858/47955876-0028b380-dfa7-11e8-849d-59e8c55b7808.png)

**Comment by rudnitskih** [comment]
On devices with small height  
![image](https://user-images.githubusercontent.com/8848858/47956076-cdcb8600-dfa7-11e8-94b6-8b5cc2b4f525.png)

**Comment by Stan0men** [comment]
В якомусь із комітів, додав топ для трикутника в % і тепер все виглядає добре для будь яких екранів

**Comment by rudnitskih** [comment]
😢

![image](https://user-images.githubusercontent.com/8848858/48121706-52572680-e27e-11e8-9528-91b8685dafb8.png)
